import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientRootLayout from "./RootLayout";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "To Do List | Fikar-Proj",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ClientRootLayout data-new-gr-c-s-check-loaded='14.1211.0'>
					{children}
				</ClientRootLayout>
			</body>
		</html>
	);
}
